spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

server:
  port: 8081
  servlet:
    encoding:
      force-response: true
    session:
      timeout: 30m

logging:
  level:
    com.my.studyRecord: trace
    org.springframework.security: debug