spring:
  profiles:
    include: secret
    active: dev

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        use_sql_comments: true
  mvc:
    async:
      request-timeout: 30000000

summarization:
  chunk:
    size: 1500


