spring:
  profiles:
    include: secret
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        use_sql_comments: true